### ISSUE TITLE
--prod Fehler abhängig von der TypeScript Version

### ISSUE THREAD

**Issue by lkstnr** [University-of-Potsdam-MM/Mobile.UP#633]
https://forum.ionicframework.com/t/build-in-prod-mode-cannot-find-module/132231

App bleibt im Splashscreen hängen wenn ich mit --prod baue.
Bei mir tritt mit TypeScript 2.9.2 und 3.2.2 folgender Fehler auf

>  Uncaught Error: Cannot find module “.”
at vendor.js:1
at vendor.js:1
at Object. (vendor.js:1)
at e (vendor.js:1)
at Object. (main.js:1)
at e (vendor.js:1)
at window.webpackJsonp (vendor.js:1)
at main.js:1

Habe jetzt wieder TypeScript 2.4.2 installiert, damit funktioniert es.

**Comment by lkstnr** [comment]
Tritt bei mir jetzt nicht mehr auf. Wahrscheinlich haben wir damals nicht alle Packages geupdated.

**Comment by alekiy** [comment]
Ist bei mir gerade wieder aufgetreten :P 

Typescript steht mit 3.2.4 nur als devDependency. Ich vermute es liegt daran.

**Comment by lkstnr** [comment]
Ich bin auch gerade dabei alles auf Ionic 4 umzustellen, vielleicht klappt es nicht mit Ionic 3 ... ?

**Comment by alekiy** [comment]
```
 Error: The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.3.3 was found instead. 
Error: The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.3.3 was found instead.
    at checkVersion (/var/www/html/mobileup/node_modules/@angular/compiler-cli/src/transformers/program.js:824:19)
    at new AngularCompilerProgram (/var/www/html/mobileup/node_modules/@angular/compiler-cli/src/transformers/program.js:88:13)
    at Object.createProgram (/var/www/html/mobileup/node_modules/@angular/compiler-cli/src/transformers/program.js:836:16)
    at Object.createProgram (/var/www/html/mobileup/node_modules/@angular/compiler-cli/src/ngtools_api2.js:36:26)
    at /var/www/html/mobileup/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:210:40
    at step (/var/www/html/mobileup/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/var/www/html/mobileup/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/var/www/html/mobileup/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
[ERROR] An error occurred while running subprocess ionic-app-scripts.
```

**Comment by lkstnr** [comment]
Ich habe Typescript@3.2.4

**Comment by alekiy** [comment]
Ich auch aber als devDependency nicht oben bei den normalen Dependencies in package.json gelistet oder? ;)

**Comment by lkstnr** [comment]
Ich hab's auch nur als devDependency. Komisch..

**Comment by lkstnr** [comment]
Für Ionic 4 ist die aktuellste Version Typescript@3.2.4
